In [1]:
# Setup: imports and paths
import pandas as pd
from pathlib import Path

root = Path(r"c:\Users\USER\OneDrive\Desktop\realtyAI")
input_path = root / "test.csv"
output_path = root / "housetest.csv"

# Values to consider as missing (NA)
NA_VALS = [
    "", " ", "NA", "N/A", "na", "null", "NULL", "None", "none", "-", "--", "\t", "\r", "\n"
]

print("Input:", input_path)
print("Output:", output_path)

Input: c:\Users\USER\OneDrive\Desktop\realtyAI\test.csv
Output: c:\Users\USER\OneDrive\Desktop\realtyAI\housetest.csv

In [2]:
# Load CSV and show initial info
print("Reading:", input_path)
df = pd.read_csv(input_path, na_values=NA_VALS, keep_default_na=True, skipinitialspace=True)
print("Initial shape:", df.shape)
print("Columns (first 10):", list(df.columns)[:10])
df.head(3)

Reading: c:\Users\USER\OneDrive\Desktop\realtyAI\test.csv
Initial shape: (1459, 80)
Columns (first 10): ['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities']

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal

In [3]:
# Clean: trim strings, normalize empties, drop all-empty rows/cols
# 1) Trim column headers
df.columns = [str(c).strip() for c in df.columns]

# 2) Trim string/object cells
obj_cols = df.select_dtypes(include=["object"]).columns
if len(obj_cols) > 0:
    df[obj_cols] = df[obj_cols].apply(lambda col: col.astype("string").str.strip())

# 3) Replace remaining empty strings with <NA>
df = df.replace({"": pd.NA})

# 4) Drop columns and rows that are entirely NA
cols_before = df.shape[1]
rows_before = df.shape[0]

df = df.dropna(axis=1, how='all')
df = df.dropna(axis=0, how='all')

cols_after = df.shape[1]
rows_after = df.shape[0]

print({
    "shape_after": df.shape,
    "dropped_cols": cols_before - cols_after,
    "dropped_rows": rows_before - rows_after,
})

{'shape_after': (1459, 80), 'dropped_cols': 0, 'dropped_rows': 0}

In [4]:
# Save cleaned data and quick preview
print("Saving to:", output_path)
df.to_csv(output_path, index=False)

# Confirm file saved and show a small preview
from pathlib import Path
p = Path(output_path)
print("Exists:", p.exists(), "Size (bytes):", p.stat().st_size if p.exists() else None)
print("Final shape:", df.shape)
df.head(5)

Saving to: c:\Users\USER\OneDrive\Desktop\realtyAI\housetest.csv
Exists: True Size (bytes): 466791
Final shape: (1459, 80)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,<NA>,Reg,Lvl,AllPub,...,120,0,<NA>,MnPrv,<NA>,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,<NA>,IR1,Lvl,AllPub,...,0,0,<NA>,<NA>,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,<NA>,IR1,Lvl,AllPub,...,0,0,<NA>,MnPrv,<NA>,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,<NA>,IR1,Lvl,AllPub,...,0,0,<NA>,<NA>,<NA>,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,<NA>,IR1,HLS,AllPub,...,144,0,<NA>,<NA>,<NA>,0,1,2010,WD,Normal